const Users = [
  {
    id: 1,
    firstname: 'Netphantom',
    lastname: 'Crook',
    email: 'nana@gmail.com',
    password: 'crook@123',
    address: 'Kigali Nyarugenge',
    bio: 'born in june 1993',
    occupation: 'Web Designer',
    expertise: 'PHP',
    isadmin: true,
    isMentor: true,
  },
  {
    id: 2,
    firstname: 'Netphantom',
    lastname: 'Crook',
    email: 'polo@gmail.com',
    password: 'crook@123',
    address: 'Kigali Nyarugenge',
    bio: 'born in june 1993',
    occupation: 'Doctory',
    expertise: 'Heart sugery',
    isadmin: false,
    isMentor: false,
  },
  {
    id: 3,
    firstname: 'Netphantom',
    lastname: 'Crook',
    email: 'netphantom@gmail.com',
    password: 'crook@123',
    address: 'Kigali Nyarugenge',
    bio: 'born in june 1993',
    occupation: 'Programmer',
    expertise: 'Python',
    isadmin: true,
    isMentor: false,
  },
];

export default Users;
